name: Build and Deploy Docs on Release

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Build documentation
        run: |
          PYTHONPATH=. python -m pyxora docs build
          mkdir -p deploy/docs
          cp -r docs/* deploy/docs/

      - name: Deploy to Website Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: pyxora/website           
          personal_token: ${{ secrets.WEB_TOKEN }}    
          publish_dir: ./deploy
          publish_branch: main
          keep_files: true
